version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: app_postgres_local
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pwd
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: