spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: local_user
    password: local_pwd